[mgr]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "size"
show_symlink = true
scrolloff = 8
mouse_events = [ "scroll" ]

[preview]
wrap = "yes"
tab_size = 2
max_width = 1600
max_height = 1600
image_delay = 20
image_filter = "triangle"
image_quality = 75
cache_dir = ""

[plugin]
prepend_previewers = [
  { mime = "application/pdf", run = "file" }
]
prepend_spotters = [
  { mime = "application/pdf", run = "file" }
]

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]
play = [
  { run = 'open "$@"', orphan = true, for = "macos" }
]
reveal = [
  { run = 'open -R "$1"', orphan = true, for = "macos" }
]

[open]
prepend_rules = [
  { name = "*.md", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.lua", use = "edit" },
  { name = "*.zsh", use = "edit" },
  { name = "*.pdf", use = "play" }
]
